# nginx proxy address - http://172.17.0.1:8097

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  statping:
    image: statping/statping:latest
    container_name: statping-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - statping
    ports:
      - "8097:8097"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./rootfs/config/statping:/config
      - ./rootfs/data/statping:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8097"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  statping:
    external: false
